/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniObjectPassing */

#ifndef _Included_JniObjectPassing
#define _Included_JniObjectPassing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniObjectPassing
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniObjectPassing_modifyInstanceVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
