/* DO NOT EDIT THIS FILE - it is machine generated */
#include </usr/lib/jvm/java-8-openjdk-amd64/include/jni.h>
/* Header for class JniObjectPassing */

#ifndef _Included_JniObjectPassing
#define _Included_JniObjectPassing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniObjectPassing
 * Method:    sum
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_JniObjectPassing_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
