/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SortingArray */

#ifndef _Included_SortingArray
#define _Included_SortingArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SortingArray
 * Method:    sorting
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_SortingArray_sorting
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
