/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniExceptions */

#ifndef _Included_JniExceptions
#define _Included_JniExceptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniExceptions
 * Method:    intMethod
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JniExceptions_intMethod
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JniExceptions
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_JniExceptions_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     JniExceptions
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniExceptions_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JniExceptions
 * Method:    doIt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniExceptions_doIt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
