/* DO NOT EDIT THIS FILE - it is machine generated */
#include </usr/lib/jvm/java-8-openjdk-amd64/include/jni.h>
/* Header for class JNIDemo */

#ifndef _Included_JNIDemo
#define _Included_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDemo
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIDemo_display
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
